# Generated by Django 5.1.7 on 2025-04-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
