# Generated by Django 5.1.7 on 2025-04-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0002_utilisateur_role_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='default_role', max_length=255),
        ),
    ]
