# Generated by Django 5.1.7 on 2025-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0003_alter_utilisateur_role_note_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('prof', 'Professeur')], default='etudiant', max_length=50),
        ),
    ]
