# Generated by Django 5.1.7 on 2025-04-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='note',
            name='student',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='note',
            name='value',
        ),
        migrations.AddField(
            model_name='note',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PNEAPP.matiere'),
        ),
        migrations.AddField(
            model_name='note',
            name='mention',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.FloatField(null=True),
        ),
    ]
