# Generated by Django 5.1.7 on 2025-04-06 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0003_etudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_saisie',
        ),
        migrations.AddField(
            model_name='note',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='mention',
            field=models.CharField(choices=[('TB', 'Très Bien'), ('B', 'Bien'), ('AB', 'Assez Bien'), ('P', 'Passable'), ('I', 'Insuffisant')], max_length=2),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
