# Generated by Django 4.2 on 2025-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNEAPP', '0004_remove_note_date_saisie_note_date_ajout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
